import { DatabaseService } from '@modules/database/service';
import {
  ForbiddenException,
  Injectable,
  Logger,
  NotFoundException,
  UnauthorizedException,
} from '@nestjs/common';
import { LessonUpdateDTO, LessonUpdateStatusDto } from './dto/lesson';
import { CourseNotFoundException } from '@modules/course/exception';
import { VideoService } from '@modules/video/service';
import { MuxService } from 'src/config/mux';
import { VideoBadRequestException } from '@modules/video/exception';

@Injectable()
export class LessonService {
  private readonly logger: Logger = new Logger(LessonService.name);
  constructor(
    private readonly databaseService: DatabaseService,
    private readonly videoService: VideoService,
    private readonly muxService: MuxService,
  ) {}
  async updateStatus({
    lessonId,
    accountId,
    published,
  }: LessonUpdateStatusDto) {
    if (!accountId)
      throw new ForbiddenException(
        "You don't have permission to update not own lesson",
      );

    const existedCourse = await this.databaseService.course.findFirst({
      where: {
        createdById: accountId,
      },
    });
    if (!existedCourse)
      throw new CourseNotFoundException(
        'Course does not exist with user ' + accountId,
      );

    const existedLesson = await this.databaseService.lesson.findFirst({
      where: { id: lessonId, courseId: existedCourse.id },
    });

    if (!existedLesson)
      throw new NotFoundException(`This lesson ${lessonId} not found`);

    return await this.databaseService.lesson.update({
      where: { id: existedLesson.id },
      data: {
        published: published,
      },
    });
  }
  // async updateLesson(data: LessonUpdateDTO, userId: string) {
  //   const { courseId, lessonId, videoUrl, thumbnailUrl, ...values } = data;
  //   if (!userId) {
  //     throw new UnauthorizedException('Unauthorized');
  //   }

  //   const courseOwner = await this.databaseService.course.findFirst({
  //     where: {
  //       id: courseId,
  //       createdById: userId,
  //     },
  //   });
  //   if (!courseOwner)
  //     throw new CourseNotFoundException(`Course ${courseId} does not exist`);

  //   const lesson = await this.databaseService.lesson.update({
  //     where: {
  //       id: lessonId,
  //     },
  //     data: {
  //       ...values,
  //     },
  //     include: {
  //       videos: { include: { muxData: true } },
  //       usersCompleted: true,
  //     },
  //   });

  //   if (videoUrl && thumbnailUrl) {
  //     const chapter = await this.videoService.create(
  //       {
  //         title: values.name,
  //         courseId,
  //         videoUrl,
  //         duration: 10,
  //         thumbnailUrl,
  //         position: 0,
  //         lessonId: lesson.id,
  //         ...data,
  //       },
  //       userId,
  //     );

  //     /*
  //        Find if the chapter already have an uploaded video in the database
  //        by checking if the id of the chapter (chapterId) matched a certain
  //        muxData in the database. If so, delete the existingMuxData on MUX
  //        and in the database
  //    */
  //     const existingMuxData = await this.databaseService.muxData.findFirst({
  //       where: {
  //         videoId: chapter.id,
  //       },
  //     });

  //     if (existingMuxData) {
  //       // await Video.Assets.del(existingMuxData.assetId);
  //       await this.muxService.deleteAsset(existingMuxData.assetId);
  //       await this.databaseService.muxData.delete({
  //         where: {
  //           id: existingMuxData.id,
  //         },
  //       });
  //     }

  //     /*
  //         Start to upload the videoUrl of the chapter (generated by the UploadThing)
  //         into MUX
  //     */
  //     const asset = await this.muxService.createAssetFromUrl(videoUrl);

  //     /*
  //         Once the upload of videoUrl of the chapter into MUX has finished proceed
  //         in storing the muxData into the database
  //     */
  //     await this.databaseService.muxData.create({
  //       data: {
  //         videoId: chapter.id,
  //         assetId: asset.id,
  //         playbackId: asset.playback_ids?.[0]?.id,
  //       },
  //     });
  //   }

  //   return lesson;
  // }
  async updateLesson(data: LessonUpdateDTO, userId: string) {
    const { courseId, lessonId, videoUrl, thumbnailUrl, ...values } = data;

    if (!userId) {
      throw new UnauthorizedException('Unauthorized');
    }

    // 1. Check course ownership
    const courseOwner = await this.databaseService.course.findFirst({
      where: {
        id: courseId,
        createdById: userId,
      },
    });

    if (!courseOwner) {
      throw new CourseNotFoundException(`Course ${courseId} does not exist`);
    }

    // 2. Update lesson info
    const lesson = await this.databaseService.lesson.update({
      where: {
        id: lessonId,
      },
      data: {
        ...values,
      },
      include: {
        videos: { include: { muxData: true } },
        usersCompleted: true,
      },
    });

    // 3. Handle video (ONLY if provided)
    if (videoUrl && thumbnailUrl) {
      // Find existing video of this lesson
      const existingVideo = await this.databaseService.video.findFirst({
        where: {
          lessonId: lesson.id,
        },
        include: {
          muxData: true,
        },
      });

      let video = null;

      if (existingVideo) {
        // ✅ UPDATE existing video
        video = await this.databaseService.video.update({
          where: {
            id: existingVideo.id,
          },
          data: {
            title: values.name,
            videoUrl,
            thumbnail: thumbnailUrl,
          },
        });

        // Delete old MUX data if exists
        if (existingVideo.muxData) {
          await this.muxService.deleteAsset(existingVideo.muxData.assetId);

          await this.databaseService.muxData.delete({
            where: {
              id: existingVideo.muxData.id,
            },
          });
        }
      } else {
        // ✅ CREATE new video (only if none exists)
        video = await this.videoService.create(
          {
            title: values.name,
            description: lesson.description,
            courseId,
            videoUrl,
            duration: 10,
            thumbnailUrl,
            position: 0,
            lessonId: lesson.id,
          },
          userId,
        );
      }

      try {
        // await this.databaseService.video.update({
        //   where: { id: video.id },
        //   data: { status: 'UPLOADING' },
        // });

        // Upload to MUX
        const asset = await this.muxService.createAssetFromUrl(videoUrl);

        // Save mux data
        await this.databaseService.muxData.create({
          data: {
            videoId: video.id,
            assetId: asset.id,
            playbackId: asset.playback_ids?.[0]?.id,
          },
        });
      } catch (error) {
        await this.databaseService.video.update({
          where: { id: video.id },
          data: { status: 'FAILED' },
        });

        throw error;
      }
    }

    return lesson;
  }
  async reorderLessons(
    courseId: string,
    userId: string,
    list: { id: string; position: number }[],
  ) {
    // Check ownership
    const courseOwner = await this.databaseService.course.findFirst({
      where: { id: courseId, createdById: userId },
    });

    if (!courseOwner) {
      throw new CourseNotFoundException(courseId);
    }

    const lessonIds = list.map((i) => i.id);

    const lessons = await this.databaseService.lesson.findMany({
      where: {
        id: { in: lessonIds },
        courseId,
      },
    });

    if (lessons.length !== list.length) {
      throw new Error('Some lessons not found or not in this course');
    }

    // Transaction reorder
    await this.databaseService.$transaction(
      list.map((item) =>
        this.databaseService.lesson.update({
          where: { id: item.id },
          data: { position: item.position },
        }),
      ),
    );

    return { message: 'Lessons reordered successfully' };
  }

  async reorderVideos(
    lessonId: string,
    userId: string,
    list: { id: string; position: number }[],
  ) {
    // Check lesson ownership via course
    const lesson = await this.databaseService.lesson.findFirst({
      where: {
        id: lessonId,
        course: {
          createdById: userId,
        },
      },
    });

    if (!lesson) {
      throw new CourseNotFoundException('Lesson not found or unauthorized');
    }

    const videoIds = list.map((i) => i.id);

    const videos = await this.databaseService.video.findMany({
      where: {
        id: { in: videoIds },
        lessonId, // 🔥 IMPORTANT: ensure same lesson
      },
    });

    if (videos.length !== list.length) {
      throw new VideoBadRequestException(
        'Some videos not found or not in this lesson',
      );
    }

    await this.databaseService.$transaction(
      list.map((item) =>
        this.databaseService.video.update({
          where: { id: item.id },
          data: { position: item.position },
        }),
      ),
    );

    return { message: 'Videos reordered successfully' };
  }
}
