export const configKeys = {
  POSTGRES_HOST: 'POSTGRES_HOST',
  POSTGRES_PORT: 'POSTGRES_PORT',
  POSTGRES_USER: 'POSTGRES_USER',
  POSTGRES_PASSWORD: 'POSTGRES_PASSWORD',
  POSTGRES_DATABASE: 'POSTGRES_DATABASE',
  JWT_SECRET: 'JWT_SECRET',
  JWT_EXPIRATION_TIME: 'JWT_EXPIRATION_TIME',
  ADMIN_PASSWORD: 'ADMIN_PASSWORD',
  HTTP_SERVER_PORT: 'HTTP_SERVER_PORT',
  MODE: 'MODE',
  CLIENT_URL: 'CLIENT_URL',
};
