@serverUrl=http://localhost:3001

###

POST {{serverUrl}}/roles
Content-Type: application/json

{
    "roles": ["ADMIN", "MOD"]
}
###
GET {{serverUrl}}/accounts
###

Get {{serverUrl}}/accounts/334fa5f4-c987-4c70-9460-85e515075e46
###